#!/bin/bash
# Arjienx DNSTT Termux Script Installer
#--------------------------------

rm -rf install

apt-get update
apt-get install -y dnsutils nano

wget --no-check-certificate -O ../usr/bin/menu https://raw.githubusercontent.com/Ysilven/termux-script/main/menu && chmod +x ../usr/bin/menu

echo " Installation Completed."
echo " Arjienx DNSTT Script v0.1.2"
echo
echo " Arjienx-PHC"
echo " enter is the key to back quickly and start query testing instantly."
echo " Type 'menu' and enter to run the dnstt termux script"
